package com.jarvis.mobile;

import android.app.*; import android.content.*; import android.media.AudioManager; import android.net.Uri; import android.os.*;
import org.json.*;

/** Persistent foreground command channel. The PC JARVIS server remains the decision-maker. */
public class CommandPoller extends Service {
 private Handler h; private Runnable loop;
 @Override public int onStartCommand(Intent i,int flags,int id){createChannel();startForeground(9,new Notification.Builder(this,"jarvis_agent").setContentTitle("JARVIS agent active").setContentText("Listening for approved commands and events").setSmallIcon(android.R.drawable.ic_menu_manage).build());
  h=new Handler(Looper.getMainLooper());loop=new Runnable(){public void run(){poll();h.postDelayed(this,2000);}};h.post(loop);return START_STICKY;}
 private void poll(){new Thread(()->{try{String raw=Bridge.get(this,"/api/mobile/commands?device_id="+Uri.encode(Device.id(this)));if(raw==null||raw.isEmpty())return;JSONObject root=new JSONObject(raw);JSONArray a=root.optJSONArray("commands");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);String id=c.optString("id");boolean ok=execute(c);Bridge.post(this,"/api/mobile/command-result","{\"id\":"+Bridge.q(id)+",\"ok\":"+ok+"}");}}catch(Exception ignored){}} ,"jarvis-command").start();}
 private boolean execute(JSONObject c){try{String a=c.optString("action").toUpperCase();if(a.equals("HOME"))return JarvisAccessibilityService.global(1);if(a.equals("BACK"))return JarvisAccessibilityService.global(2);if(a.equals("RECENTS"))return JarvisAccessibilityService.global(3);if(a.equals("NOTIFICATIONS"))return JarvisAccessibilityService.global(4);if(a.equals("QUICK_SETTINGS"))return JarvisAccessibilityService.global(5);if(a.equals("POWER_DIALOG"))return JarvisAccessibilityService.global(6);if(a.equals("TAP"))return JarvisAccessibilityService.tap(c.optInt("x"),c.optInt("y"));if(a.equals("SCROLL_DOWN"))return JarvisAccessibilityService.scroll(false);if(a.equals("SCROLL_UP"))return JarvisAccessibilityService.scroll(true);if(a.equals("SPEAK")){JarvisAssistantServiceProxy.speak(this,c.optString("text"));return true;}if(a.equals("READ_LAST_WHATSAPP")){JarvisAssistantServiceProxy.speak(this,getSharedPreferences("jarvis_notifications",MODE_PRIVATE).getString("whatsapp_last","No recent WhatsApp message is available."));return true;}if(a.equals("SWIPE"))return JarvisAccessibilityService.swipe(c.optInt("x1"),c.optInt("y1"),c.optInt("x2"),c.optInt("y2"),c.optLong("duration",500));if(a.equals("TYPE"))return JarvisAccessibilityService.type(c.optString("text"));if(a.equals("READ_SCREEN")){JarvisAccessibilityService.readScreenText(this);return true;}if(a.equals("OPEN_URI")){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(c.optString("uri"))).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));return true;}if(a.equals("LAUNCH_PACKAGE")){Intent x=getPackageManager().getLaunchIntentForPackage(c.optString("package"));if(x==null)return false;startActivity(x.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));return true;}if(a.equals("VOLUME_UP")||a.equals("VOLUME_DOWN")){AudioManager m=(AudioManager)getSystemService(AUDIO_SERVICE);m.adjustVolume(a.equals("VOLUME_UP")?AudioManager.ADJUST_RAISE:AudioManager.ADJUST_LOWER,AudioManager.FLAG_SHOW_UI);return true;}return false;}catch(Exception e){return false;}}
 @Override public void onDestroy(){if(h!=null&&loop!=null)h.removeCallbacks(loop);super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel("jarvis_agent","JARVIS Agent",NotificationManager.IMPORTANCE_LOW));}
}
